services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./.env
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - /node_modules
        - action: rebuild
          path: package.json
          target: /app

  db:
    image: postgres:17-alpine
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: